version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      # - sh scripts/install-script.sh
      - echo "Pre-build script is running..."
      - ls -la
      -  # Copy source code from S3 bucket to src directory
      - echo "Copying source code from S3 bucket to src directory"
      - mkdir -p src/rebuild
      - aws s3 cp s3://lambda-project-bundle-source/ src/rebuild/ --recursive
      - ls -la
      - ls -la src/rebuild
  pre_build:
    commands:
      # - sh scripts/pre-build-script.sh
      - echo "Install script is running..."
      - ls -la
      -  # Install AWS CLI and CDK
      - echo "Installing dependencies"
      - npm install -g aws-cdk@2
      - npm install
      - npm install --save-dev @types/node
      - echo "Check versions"
      - node -v
      - npm -v
      - npx -v
      - aws --version
      - cdk --version
      -  # Bootstrap CDK
      - cdk bootstrap aws://650251698778/ap-northeast-1
  build:
    commands:
      # - sh scripts/build-script.sh
      - echo "Build phase running..."
      - echo "Deploying CDK stack"
      - npm run deploy-require-approval
