version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Install phase running..."
      - ls -la
      -  # Install AWS CLI and CDK
      - echo "Installing dependencies"
      - npm install -g aws-cdk@2
      - npm install
      - npm install --save-dev @types/node
      - npm install -g unzipper
      - echo "Check versions"
      - node -v
      - npm -v
      - npx -v
      - aws --version
      - cdk --version
  pre_build:
    commands:
      - echo "Pre-build script is running..."
      - mkdir -p src/rebuild
      - ls -la
      # Copy file rebuild.zip from S3 bucket to home directory
      - aws s3 cp s3://lambda-project-bundle-source/rebuild.zip .
      - echo "Unzipping rebuild.zip"
      - unzip rebuild.zip -d src/rebuild
      - ls -la
      - ls -la src/rebuild
      # Bootstrap CDK
      - cdk bootstrap aws://650251698778/ap-northeast-1
  build:
    commands:
      - echo "Build phase running..."
      - echo "Deploying CDK stack"
      - npm run deploy-require-approval
